### ISSUE TITLE
Return contributor balance with contributor data

### ISSUE THREAD

**Issue by bumi** [67P/truffle-kredits#13]
To save one extra request to get the balance of a contributor address we could try to return the balance from the token contract directly with the contributor data from the contributors contract.

**Comment by skddc** [comment]
Keep in mind that on the dashboard, and for all matters regarding "how much did the person contribute", we need to count tokens *issued* from the minting events, as opposed to tokens *currently in possession of*.

**Comment by bumi** [comment]
yep, we need to calculate in the frontend. the contract does not have access to those sadly. - (which we might need to rethink in the future, depending on what we want to do with that number)

**Comment by skddc** [comment]
That's what we have our kredits JS module for. I meant it should go in there. Wrong repo here. :)

**Comment by bumi** [comment]
this is what I am talking about: #14

**Comment by skddc** [comment]
:+1:
