### ISSUE TITLE
Import Operator contract

### ISSUE THREAD

**Issue by bumi** [67P/truffle-kredits#3]
The operator contract so far was managing the proposals.

We could think about refactoring the contract to use a `delegatecall` concept and to deploy a contract for every proposal.

**Comment by fsmanuel** [comment]
Is there a kind of list of proposal types? What are the base attributes of a proposal?

**Comment by bumi** [comment]
There is this schema: https://github.com/67P/kosmos-schemas/blob/master/schemas/contribution.json

**Comment by skddc** [comment]
That schema is only describing the contribution in a contribution proposal. I think the question is, if there are types of proposals that are not about contributions, right?

**Comment by fsmanuel** [comment]
@skddc you are right! For example the voting on a new token contract or what ever could be a proposal as well.

Does a contribution equals a proposal?

**Comment by skddc** [comment]
Yes, at the moment that's how it works. In fact, a proposal is purely a *proposal to issue kredits*. Everything else is meta data.

I think that's an important thing to keep in mind about blockchain development: we want the most basic data building blocks possible to live on-chain, and everything else should just be implementation details of clients. For example the chain doesn't really have to know why the kredits were issued, it only needs to reference an IPFS object that contains the reason. But the format of that object is entirely up to clients to define and interpret.

**Comment by fsmanuel** [comment]
I was talking to @bumi about that once. I like that concept and how you use IPFS to store the meta data/informations.

**Comment by fsmanuel** [comment]
This one is done, right?

**Comment by bumi** [comment]
yep, this is done.
